### PR TITLE
Added functionality to clear/ retry failed jobs.

### PR DESCRIPTION
**Pull request by PATROMO**
Similar to the ruby resque-web gem.

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Some conflicts here before it can be merged :)

**Comment by PATROMO** [comment]
@PhilETaylor I want resolved the conflicts and destroy this pull request. Because in my fork I meraged alle the branches by my self. Should I create a new pull-request? :(

**Comment by PhilETaylor** [comment]
Yes please.

**Comment by PATROMO** [comment]
@PhilETaylor damn. You was to fast - I have fix it :D

**Comment by PhilETaylor** [comment]
Done :)

**Comment by PATROMO** [comment]
Thanks. 👍

**Pull request merged**
